In [130]:
import pandas as pd
import os

os.chdir("C:/Users/Wan Hok Ming/Documents/Applied Policy Project/Crunchbase")

In [140]:
combined = pd.DataFrame()
directory = "Finished"
files = os.listdir(directory)

for xls in files:
    if xls.endswith(".xlsx"):
        file_path = os.path.join(directory, xls)
        tbc = pd.read_excel(file_path)
        investor_name = os.path.splitext(xls)[0]
        tbc['Investor'] = investor_name        
        tbc = tbc.reindex(columns=['Investor'] + [col for col in tbc.columns if col != 'Investor'])        
        combined = pd.concat([combined, tbc])

In [132]:
combined = combined.reset_index(drop=True)
display(combined)

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries
0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware
1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...
2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...
3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...
4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...
...,...,...,...,...,...,...,...,...
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...
1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS
1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech
1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS
1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery

In [133]:
combined.to_csv('merged_investment.csv', index=False)

In [134]:
combined = pd.read_csv("merged_investment.csv")

In [135]:
import re

pattern = r'(\d*\.?\d+)([KMBT]?)'
numeric_values = combined['Money Raised'].apply(lambda x: re.findall(pattern, str(x)))
print(numeric_values)

0          [(11, M)]
1         [(2.7, B)]
2         [(9.4, M)]
3          [(23, M)]
4         [(590, M)]
            ...
1376    [(617.1, K)]
1377       [(50, M)]
1378       [(13, M)]
1379       [(35, M)]
1380      [(6.6, M)]
Name: Money Raised, Length: 1381, dtype: object

In [136]:
def process_numeric_values(matches):
    if matches:
        value, suffix = matches[0]
        if suffix == 'K':
            return float(value) * 1e3
        elif suffix == 'M':
            return float(value) * 1e6
        elif suffix == 'B':
            return float(value) * 1e9
        elif suffix == 'T':
            return float(value) * 1e12
        else:
            return float(value)
    else:
        return None
    
numeric_values_processed = numeric_values.apply(process_numeric_values)
print(numeric_values_processed)

0       1.100000e+07
1       2.700000e+09
2       9.400000e+06
3       2.300000e+07
4       5.900000e+08
            ...
1376    6.171000e+05
1377    5.000000e+07
1378    1.300000e+07
1379    3.500000e+07
1380    6.600000e+06
Name: Money Raised, Length: 1381, dtype: float64

In [137]:
remaining_elements = combined['Money Raised'].apply(lambda x: re.sub(pattern, '', str(x)))
print(remaining_elements)

0         $
1         $
2         $
3         $
4         $
       ...
1376    CA$
1377      $
1378      $
1379      $
1380      $
Name: Money Raised, Length: 1381, dtype: object

In [138]:
combined["Money Raised (Currency Type)"] = remaining_elements
combined['Money Raised (Values)'] = numeric_values_processed
combined

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values)
0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware,$,1.100000e+07
1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...,$,2.700000e+09
2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...,$,9.400000e+06
3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...,$,2.300000e+07
4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...,$,5.900000e+08
...,...,...,...,...,...,...,...,...,...,...
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CA$,6.171000e+05
1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,$,5.000000e+07
1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech,$,1.300000e+07
1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,$,3.500000e+07
1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery,$,6.600000e+06

In [62]:
currency_type = combined['Money Raised (Currency Type)'].value_counts()
currency_type_freq = pd.DataFrame(currency_type)
currency_type_freq

                              count
Money Raised (Currency Type)
$                               941
SAR                              99
??                                9
Ã¢â€šÂ¬                               8
çž¿                                 8
CNçž¼                               6
Ã‚Â£                                5
CA$                               5
Ã¢â€šÂ¹                               4
CHF                               4
??M                               3
A$                                2
NOK                               2
Ã¢â€šÂ©                               1
R$                                1
çž¼                                 1
CNÃ‚Â¥                              1

In [79]:
# Inspect currency type with weird characters

unknown_currency = combined[combined["Money Raised (Currency Type)"] == "CAN"]
unknown_currency

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values)
362,KAUST Innovation Fund,2017-02-13,QD Solar Inc.,No,Series A - QD Solar Inc.,CA$2.5M,"Toronto, Ontario, Canada",Energy\nManufacturing\nNanotechnology\nRenewab...,CAN,2500000.0
1373,Zaeem Shaukat Mirza,2021-05-20,Caary,No,Seed Round - Caary,CA$5.4M,"Toronto, Ontario, Canada",Credit Cards\nFinancial Services\nFinTech\nLen...,CAN,5400000.0
1374,Zaeem Shaukat Mirza,2021-04-08,Treasure Card,No,Seed Round - Treasure Card,CA$185.7K,"Toronto, Ontario, Canada",Debit Cards\nEducation\nFinancial Services,CAN,185700.0
1375,Zaeem Shaukat Mirza,2020-11-15,Back to Basics Coop,No,Funding Round - Back to Basics Coop,CA$300K,NaN,Meat and Poultry\nReal Estate Investment,CAN,300000.0
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CAN,617100.0

In [83]:
# Replace unknown currency characters with actual currency abbr

combined.loc[combined['Money Raised (Currency Type)'] == '$', 'Money Raised (Currency Type)'] = "USD"
combined.loc[combined['Money Raised (Currency Type)'] == 'çž¿', 'Money Raised (Currency Type)'] = "GBP"
combined.loc[combined['Money Raised (Currency Type)'] == 'CNçž¼', 'Money Raised (Currency Type)'] = "CNH"
combined.loc[combined['Money Raised (Currency Type)'] == 'CNÃ‚Â¥', 'Money Raised (Currency Type)'] = "CNH"
combined.loc[combined['Money Raised (Currency Type)'] == 'çž¼', 'Money Raised (Currency Type)'] = "JPY"
combined.loc[combined['Money Raised (Currency Type)'] == 'Ã¢â€šÂ¬', 'Money Raised (Currency Type)'] = "EUR"
combined.loc[combined['Money Raised (Currency Type)'] == 'Ã‚Â£', 'Money Raised (Currency Type)'] = "GBP"
combined.loc[combined['Money Raised (Currency Type)'] == 'CA$', 'Money Raised (Currency Type)'] = "CAN"
combined.loc[combined['Money Raised (Currency Type)'] == 'Ã¢â€šÂ¹', 'Money Raised (Currency Type)'] = "INR"
combined.loc[combined['Money Raised (Currency Type)'] == '??M', 'Money Raised (Currency Type)'] = "EUR"
combined.loc[combined['Money Raised (Currency Type)'] == 'Ã¢â€šÂ¹', 'Money Raised (Currency Type)'] = "INR"
combined.loc[combined['Money Raised (Currency Type)'] == 'A$', 'Money Raised (Currency Type)'] = "AUD"
combined.loc[combined['Money Raised (Currency Type)'] == 'Ã¢â€šÂ©', 'Money Raised (Currency Type)'] = "KPW"
combined.loc[combined['Money Raised (Currency Type)'] == 'R$', 'Money Raised (Currency Type)'] = "BRL"
combined.loc[combined['Money Raised (Currency Type)'] == '??T', 'Money Raised (Currency Type)'] = "KPW"

combined.loc[(combined['Location'].str.contains("India")) & (combined['Money Raised (Currency Type)'] == '??'), 'Money Raised (Currency Type)'] = "INR"
combined.loc[(combined['Location'].str.contains("Korea")) & (combined['Money Raised (Currency Type)'] == '??'), 'Money Raised (Currency Type)'] = "KPW"
combined.loc[(combined['Money Raised (Currency Type)'] == '??'), 'Money Raised (Currency Type)'] = "EUR"

In [90]:
currency_type_refined = combined['Money Raised (Currency Type)'].value_counts()
currency_type_freq_refined = pd.DataFrame(currency_type_refined)
currency_type_freq_refined

                              count
Money Raised (Currency Type)
USD                             941
SAR                              99
EUR                              15
GBP                              13
INR                               7
CNH                               7
CAN                               5
CHF                               4
KPW                               3
AUD                               2
NOK                               2
BRL                               1
JPY                               1

In [91]:
import numpy as np

combined['Money Raised (Values in USD)'] = combined['Money Raised (Values)']
combined.loc[combined['Money Raised (Currency Type)'] == 'SAR', 'Money Raised (Values in USD)'] /= 3.75
combined.loc[combined['Money Raised (Currency Type)'] == 'EUR', 'Money Raised (Values in USD)'] /= 0.92
combined.loc[combined['Money Raised (Currency Type)'] == 'GBP', 'Money Raised (Values in USD)'] /= 0.79
combined.loc[combined['Money Raised (Currency Type)'] == 'INR', 'Money Raised (Values in USD)'] /= 83.48
combined.loc[combined['Money Raised (Currency Type)'] == 'CNH', 'Money Raised (Values in USD)'] /= 7.23
combined.loc[combined['Money Raised (Currency Type)'] == 'CAN', 'Money Raised (Values in USD)'] /= 1.36
combined.loc[combined['Money Raised (Currency Type)'] == 'CHF', 'Money Raised (Values in USD)'] /= 0.90
combined.loc[combined['Money Raised (Currency Type)'] == 'KPW', 'Money Raised (Values in USD)'] /= 899
combined.loc[combined['Money Raised (Currency Type)'] == 'AUD', 'Money Raised (Values in USD)'] /= 1.50
combined.loc[combined['Money Raised (Currency Type)'] == 'NOK', 'Money Raised (Values in USD)'] /= 10.81
combined.loc[combined['Money Raised (Currency Type)'] == 'BRL', 'Money Raised (Values in USD)'] /= 5.13
combined.loc[combined['Money Raised (Currency Type)'] == 'JPY', 'Money Raised (Values in USD)'] /= 156

In [92]:
combined

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values),Money Raised (Values in USD)
0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware,USD,1.100000e+07,1.100000e+07
1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...,USD,2.700000e+09,2.700000e+09
2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...,USD,9.400000e+06,9.400000e+06
3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...,USD,2.300000e+07,2.300000e+07
4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...,USD,5.900000e+08,5.900000e+08
...,...,...,...,...,...,...,...,...,...,...,...
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CAN,6.171000e+05,4.537500e+05
1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,5.000000e+07,5.000000e+07
1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech,USD,1.300000e+07,1.300000e+07
1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,3.500000e+07,3.500000e+07
1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery,USD,6.600000e+06,6.600000e+06

In [94]:
combined.to_csv("to refine currency.csv")

In [95]:
industry_group = pd.read_csv("industry-groups-crunchbase 49.csv")

In [96]:
import numpy as np

combined_industry = combined
combined_industry  = combined_industry.dropna(subset=["Industries"])

industry_group_name = []
for ind in combined_industry['Industries']: 
    if isinstance(ind, str):
        items = ind.split('\n')
        industry_group_name.append(items)
    else:
        industry_group_name.append(np.nan)

combined_industry['Industries_list'] = industry_group_name

combined_industry['industry group list'] = np.nan
combined_industry['industry group list'] = [[] for row in combined_industry['industry group list']]

C:\Users\Wan Hok Ming\AppData\Local\Temp\ipykernel_9228\3190076825.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_industry['Industries_list'] = industry_group_name
C:\Users\Wan Hok Ming\AppData\Local\Temp\ipykernel_9228\3190076825.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_industry['industry group list'] = np.nan
C:\Users\Wan Hok Ming\AppData\Local\Temp\ipykernel_9228\3190076825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_industry['industry group list'] = [[] for row in combined_industry['industry group list']]

In [97]:
industry_group_name_CR = []
for ind in industry_group['Industries']: 
    if isinstance(ind, str):
        items = ind.split(', ')
        industry_group_name_CR.append(items)
    else:
        industry_group_name_CR.append(np.nan)

industry_group['Industries_CR_list'] = industry_group_name_CR

In [98]:
combined_industry

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values),Money Raised (Values in USD),Industries_list,industry group list
0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware,USD,1.100000e+07,1.100000e+07,"[Finance, Financial Services, FinTech, Software]",[]
1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...,USD,2.700000e+09,2.700000e+09,"[Automotive, Electric Vehicle, Manufacturing, ...",[]
2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...,USD,9.400000e+06,9.400000e+06,"[Bitcoin, Cryptocurrency, Financial Exchanges,...",[]
3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...,USD,2.300000e+07,2.300000e+07,"[Billing, Finance, Financial Services, FinTech...",[]
4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...,USD,5.900000e+08,5.900000e+08,"[Aerospace, Air Transportation, Electric Vehic...",[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CAN,6.171000e+05,4.537500e+05,"[Banking, Debit Cards, Financial Exchanges, Fi...",[]
1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,5.000000e+07,5.000000e+07,"[Information Technology, Logistics, SaaS]",[]
1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech,USD,1.300000e+07,1.300000e+07,"[Banking, Financial Services, FinTech]",[]
1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,3.500000e+07,3.500000e+07,"[Information Technology, Logistics, SaaS]",[]
1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery,USD,6.600000e+06,6.600000e+06,"[Delivery, E-Commerce, Grocery]",[]

In [99]:
industry_group

,Industry Group Name,Industry Group Name URL,Industries,Industries_CR_list
0,Administrative Services,https://www.crunchbase.com/category_group/admi...,"Archiving Service, Call Center, Collection Age...","[Archiving Service, Call Center, Collection Ag..."
1,Advertising,https://www.crunchbase.com/category_group/adve...,"Ad Exchange, Ad Network, Ad Retargeting, Ad Se...","[Ad Exchange, Ad Network, Ad Retargeting, Ad S..."
2,Agriculture and Farming,https://www.crunchbase.com/category_group/agri...,"Agriculture, AgTech, Animal Feed, Aquaculture,...","[Agriculture, AgTech, Animal Feed, Aquaculture..."
3,Apps,https://www.crunchbase.com/category_group/apps...,"App Discovery, Apps, Consumer Applications, En...","[App Discovery, Apps, Consumer Applications, E..."
4,Artificial Intelligence (AI),https://www.crunchbase.com/category_group/arti...,"Artificial Intelligence (AI), Generative AI, I...","[Artificial Intelligence (AI), Generative AI, ..."
5,Biotechnology,https://www.crunchbase.com/category_group/biot...,"Bioinformatics, Biometrics, Biopharma, Biotech...","[Bioinformatics, Biometrics, Biopharma, Biotec..."
6,Blockchain and Cryptocurrency,https://www.crunchbase.com/category_group/bloc...,"Bitcoin, Blockchain, Cryptocurrency, Decentral...","[Bitcoin, Blockchain, Cryptocurrency, Decentra..."
7,Clothing and Apparel,https://www.crunchbase.com/category_group/clot...,"Apparel, Fashion, Laundry and Dry-cleaning, Li...","[Apparel, Fashion, Laundry and Dry-cleaning, L..."
8,Commerce and Shopping,https://www.crunchbase.com/category_group/comm...,"Auctions, Classifieds, Collectibles, Consumer ...","[Auctions, Classifieds, Collectibles, Consumer..."
9,Community and Lifestyle,https://www.crunchbase.com/category_group/comm...,"Adult, Baby, Cannabis, Children, Communities, ...","[Adult, Baby, Cannabis, Children, Communities,..."
10,Consumer Electronics,https://www.crunchbase.com/category_group/cons...,"Computer, Consumer Electronics, Drones, Electr...","[Computer, Consumer Electronics, Drones, Elect..."
11,Consumer Goods,https://www.crunchbase.com/category_group/cons...,"Beauty, Card and Board Games, Cleaning Product...","[Beauty, Card and Board Games, Cleaning Produc..."
12,Content and Publishing,https://www.crunchbase.com/category_group/cont...,"Blogging Platforms, Books, Content Delivery Ne...","[Blogging Platforms, Books, Content Delivery N..."
13,Data and Analytics,https://www.crunchbase.com/category_group/data...,"A/B Testing, Analytics, Application Performanc...","[A/B Testing, Analytics, Application Performan..."
14,Design,https://www.crunchbase.com/category_group/design,"CAD, Consumer Research, Data Visualization, Fa...","[CAD, Consumer Research, Data Visualization, F..."
15,Education,https://www.crunchbase.com/category_group/educ...,"Alumni, Charter Schools, College Recruiting, C...","[Alumni, Charter Schools, College Recruiting, ..."
16,Energy,https://www.crunchbase.com/category_group/ener...,"Battery, Biofuel, Biomass Energy, Clean Energy...","[Battery, Biofuel, Biomass Energy, Clean Energ..."
17,Events,https://www.crunchbase.com/category_group/even...,"Concerts, Event Management, Event Promotion, E...","[Concerts, Event Management, Event Promotion, ..."
18,Financial Services,https://www.crunchbase.com/category_group/fina...,"Accounting, Angel Investment, Asset Management...","[Accounting, Angel Investment, Asset Managemen..."
19,Food and Beverage,https://www.crunchbase.com/category_group/food...,"Alternative Protein, Bakery, Brewing, Cannabis...","[Alternative Protein, Bakery, Brewing, Cannabi..."
20,Gaming,https://www.crunchbase.com/category_group/gami...,"Card and Board Games, Casual Games, Console Ga...","[Card and Board Games, Casual Games, Console G..."
21,Government and Military,https://www.crunchbase.com/category_group/gove...,"CivicTech, Government, GovTech, Law Enforcemen...","[CivicTech, Government, GovTech, Law Enforceme..."
22,Hardware,https://www.crunchbase.com/category_group/hard...,"3D Technology, Application Specific Integrated...","[3D Technology, Application Specific Integrate..."
23,Health Care,https://www.crunchbase.com/category_group/heal...,"Addiction Treatment, Alternative Medicine, Ass...","[Addiction Treatment, Alternative Medicine, As..."
24,Information Technology,https://www.crunchbase.com/category_group/info...,"Business Information Systems, CivicTech, Cloud...","[Business Information Systems, CivicTech, Clou..."
25,Internet Services,https://www.crunchbase.com/category_group/inte...,"Cloud Computing, Cloud Data Services, Cloud In...","[Cloud Computing, Cloud Data Services, Cloud I..."
26,Lending and Investments,https://www.crunchbase.com/category_group/lend...,"Angel Investment, Banking, Commercial Lending,...","[Angel Investment, Banking, Commercial Lending..."
27,Manufacturing,https://www.crunchbase.com/category_group/manu...,"3D Printing, Advanced Materials, Foundries, In...","[3D Printing, Advanced Materials, Foundries, I..."
28,Media and Entertainment,https://www.crunchbase.com/category_group/medi...,"Advice, Animation, Art, Audio, Audiobooks, Blo...","[Advice, Animation, Art, Audio, Audiobooks, Bl..."
29,Messaging and Telecommunications,https://www.crunchbase.com/category_group/mess...,"Email, Meeting Software, Messaging, SMS, Unifi...","[Email, Meeting Software, Messaging, SMS, Unif..."
30,Mobile,https://www.crunchbase.com/category_group/mobi...,"Android, Google Glass, iOS, mHealth, Mobile, M...","[Android, Google Glass, iOS, mHealth, Mobile, ..."
31,Music and Audio,https://www.crunchbase.com/category_group/musi...,"Audio, Audio Recording and Production, Audio/V...","[Audio, Audio Recording and Production, Audio/..."
32,Natural Resources,https://www.crunchbase.com/category_group/natu...,"Biofuel, Biomass Energy, Fossil Fuels, Mineral...","[Biofuel, Biomass Energy, Fossil Fuels, Minera..."
33,Navigation and Mapping,https://www.crunchbase.com/category_group/navi...,"Geospatial, GPS, Indoor Positioning, Location ...","[Geospatial, GPS, Indoor Positioning, Location..."
34,Other,https://www.crunchbase.com/category_group/1718...,"Alumni, Association, B2B, B2C, Blockchain, Cha...","[Alumni, Association, B2B, B2C, Blockchain, Ch..."
35,Payments,https://www.crunchbase.com/category_group/paym...,"Billing, Bitcoin, Credit Cards, Cryptocurrency...","[Billing, Bitcoin, Credit Cards, Cryptocurrenc..."
36,Platforms,https://www.crunchbase.com/category_group/plat...,"Android, Facebook, Google, Google Glass, iOS, ...","[Android, Facebook, Google, Google Glass, iOS,..."
37,Privacy and Security,https://www.crunchbase.com/category_group/priv...,"Cloud Security, Corrections Facilities, Cyber ...","[Cloud Security, Corrections Facilities, Cyber..."
38,Professional Services,https://www.crunchbase.com/category_group/prof...,"Accounting, Advocacy, Business Development, Ca...","[Accounting, Advocacy, Business Development, C..."
39,Real Estate,https://www.crunchbase.com/category_group/real...,"Architecture, Building Maintenance, Building M...","[Architecture, Building Maintenance, Building ..."
40,Sales and Marketing,https://www.crunchbase.com/category_group/sale...,"Advertising, Affiliate Marketing, App Discover...","[Advertising, Affiliate Marketing, App Discove..."
41,Science and Engineering,https://www.crunchbase.com/category_group/scie...,"Advanced Materials, Aerospace, Artificial Inte...","[Advanced Materials, Aerospace, Artificial Int..."
42,Social Impact,https://www.crunchbase.com/category_group/soci...,"Advocacy, Charity, Homeless Shelter, Humanitar...","[Advocacy, Charity, Homeless Shelter, Humanita..."
43,Software,https://www.crunchbase.com/category_group/soft...,"3D Technology, Android, App Discovery, Applica...","[3D Technology, Android, App Discovery, Applic..."
44,Sports,https://www.crunchbase.com/category_group/spor...,"American Football, Baseball, Basketball, Boati...","[American Football, Baseball, Basketball, Boat..."
45,Sustainability,https://www.crunchbase.com/category_group/sust...,"Biofuel, Biomass Energy, Carbon Capture, Clean...","[Biofuel, Biomass Energy, Carbon Capture, Clea..."
46,Transportation,https://www.crunchbase.com/category_group/tran...,"Air Transportation, Automotive, Autonomous Veh...","[Air Transportation, Automotive, Autonomous Ve..."
47,Travel and Tourism,https://www.crunchbase.com/category_group/trav...,"Adventure Travel, Amusement Park and Arcade, B...","[Adventure Travel, Amusement Park and Arcade, ..."
48,Video,https://www.crunchbase.com/category_group/vide...,"Animation, Broadcasting, Film, Film Distributi...","[Animation, Broadcasting, Film, Film Distribut..."

In [100]:
# Convert industries into 49 industry group
for index1, row1 in combined_industry.iterrows():
    # Iterate through each row of df2
    for index2, row2 in industry_group.iterrows():
                for item in row1['Industries_list']:
                        if item in row2['Industries_CR_list']:
                               combined_industry.at[index1, 'industry group list'].append(row2['Industry Group Name'])

In [101]:
combined_industry

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values),Money Raised (Values in USD),Industries_list,industry group list
0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware,USD,1.100000e+07,1.100000e+07,"[Finance, Financial Services, FinTech, Software]","[Financial Services, Financial Services, Finan..."
1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...,USD,2.700000e+09,2.700000e+09,"[Automotive, Electric Vehicle, Manufacturing, ...","[Manufacturing, Transportation, Transportation..."
2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...,USD,9.400000e+06,9.400000e+06,"[Bitcoin, Cryptocurrency, Financial Exchanges,...","[Blockchain and Cryptocurrency, Blockchain and..."
3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...,USD,2.300000e+07,2.300000e+07,"[Billing, Finance, Financial Services, FinTech...","[Financial Services, Financial Services, Finan..."
4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...,USD,5.900000e+08,5.900000e+08,"[Aerospace, Air Transportation, Electric Vehic...","[Science and Engineering, Transportation, Tran..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CAN,6.171000e+05,4.537500e+05,"[Banking, Debit Cards, Financial Exchanges, Fi...","[Financial Services, Financial Services, Finan..."
1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,5.000000e+07,5.000000e+07,"[Information Technology, Logistics, SaaS]","[Information Technology, Software, Transportat..."
1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech,USD,1.300000e+07,1.300000e+07,"[Banking, Financial Services, FinTech]","[Financial Services, Financial Services, Finan..."
1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,3.500000e+07,3.500000e+07,"[Information Technology, Logistics, SaaS]","[Information Technology, Software, Transportat..."
1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery,USD,6.600000e+06,6.600000e+06,"[Delivery, E-Commerce, Grocery]","[Administrative Services, Commerce and Shoppin..."

In [102]:
industry_17 = pd.read_excel("Industy Cathegory 17 cleaned.xlsx")
industry_17

                            Theme                    Industry Group
0              Travel and Tourism                Travel and Tourism
1                          Energy                            Energy
2                   Entertainment           Media and Entertainment
3                   Entertainment                             Video
4                   Entertainment                            Gaming
5                   Entertainment                   Music and Audio
6                   Entertainment                            Events
7                       Education                         Education
8                     Real Estate                       Real Estate
9                         Finance                Financial Services
10                        Finance                          Payments
11                        Finance           Lending and Investments
12                        Finance     Blockchain and Cryptocurrency
13      Consumer Goods and Retail                 Food and Beverage
14      Consumer Goods and Retail             Commerce and Shopping
15      Consumer Goods and Retail              Consumer Electronics
16      Consumer Goods and Retail                    Consumer Goods
17      Consumer Goods and Retail              Clothing and Apparel
18                   Connectivity                 Internet Services
19                   Connectivity  Messaging and Telecommunications
20                   Connectivity            Navigation and Mapping
21                   Connectivity                            Mobile
22                 Transportation                    Transportation
23         Information Technology            Information Technology
24         Information Technology                          Software
25         Information Technology                          Hardware
26         Information Technology                              Apps
27        Engineering and Biotech           Science and Engineering
28        Engineering and Biotech                     Biotechnology
29         Design and Advertising                            Design
30         Design and Advertising                       Advertising
31         Design and Advertising                         Platforms
32         Design and Advertising            Content and Publishing
33         Design and Advertising               Sales and Marketing
34            Health and Wellness                       Health Care
35            Health and Wellness                     Social Impact
36            Health and Wellness                    Sustainability
37            Health and Wellness           Community and Lifestyle
38            Health and Wellness                            Sports
39  Manufacturing and Agriculture                     Manufacturing
40  Manufacturing and Agriculture                 Natural Resources
41  Manufacturing and Agriculture           Agriculture and Farming
42                AI and Big Data                Data and Analytics
43                AI and Big Data      Artificial Intelligence (AI)
44                AI and Big Data              Privacy and Security
45                Support Service             Professional Services
46                Support Service           Administrative Services
47        Government and Military           Government and Military
48                          Other                             Other

In [103]:
combined_industry17 = combined_industry
combined_industry17["17 Industry Categories"] = np.nan
combined_industry17["17 Industry Categories"] = [[] for row in combined_industry["17 Industry Categories"]]
combined_industry17

C:\Users\Wan Hok Ming\AppData\Local\Temp\ipykernel_9228\3028784419.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_industry17["17 Industry Categories"] = np.nan
C:\Users\Wan Hok Ming\AppData\Local\Temp\ipykernel_9228\3028784419.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_industry17["17 Industry Categories"] = [[] for row in combined_industry["17 Industry Categories"]]

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values),Money Raised (Values in USD),Industries_list,industry group list,17 Industry Categories
0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware,USD,1.100000e+07,1.100000e+07,"[Finance, Financial Services, FinTech, Software]","[Financial Services, Financial Services, Finan...",[]
1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...,USD,2.700000e+09,2.700000e+09,"[Automotive, Electric Vehicle, Manufacturing, ...","[Manufacturing, Transportation, Transportation...",[]
2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...,USD,9.400000e+06,9.400000e+06,"[Bitcoin, Cryptocurrency, Financial Exchanges,...","[Blockchain and Cryptocurrency, Blockchain and...",[]
3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...,USD,2.300000e+07,2.300000e+07,"[Billing, Finance, Financial Services, FinTech...","[Financial Services, Financial Services, Finan...",[]
4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...,USD,5.900000e+08,5.900000e+08,"[Aerospace, Air Transportation, Electric Vehic...","[Science and Engineering, Transportation, Tran...",[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CAN,6.171000e+05,4.537500e+05,"[Banking, Debit Cards, Financial Exchanges, Fi...","[Financial Services, Financial Services, Finan...",[]
1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,5.000000e+07,5.000000e+07,"[Information Technology, Logistics, SaaS]","[Information Technology, Software, Transportat...",[]
1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech,USD,1.300000e+07,1.300000e+07,"[Banking, Financial Services, FinTech]","[Financial Services, Financial Services, Finan...",[]
1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,3.500000e+07,3.500000e+07,"[Information Technology, Logistics, SaaS]","[Information Technology, Software, Transportat...",[]
1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery,USD,6.600000e+06,6.600000e+06,"[Delivery, E-Commerce, Grocery]","[Administrative Services, Commerce and Shoppin...",[]

In [104]:
for index, row in combined_industry17.iterrows():
    for item in row['industry group list']:
        for industry_group in industry_17['Industry Group']:
            if item == industry_group:
                combined_industry17.at[index, '17 Industry Categories'].append(industry_17.loc[industry_17['Industry Group'] == industry_group, 'Theme'].values[0])

In [105]:
# remove duplicate items in 17 Industry Categories

combined_industry17['17 Industry Categories'] = [list(set(list_17)) for list_17 in combined_industry17['17 Industry Categories']]

C:\Users\Wan Hok Ming\AppData\Local\Temp\ipykernel_9228\915902727.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_industry17['17 Industry Categories'] = [list(set(list_17)) for list_17 in combined_industry17['17 Industry Categories']]

In [106]:
combined_industry17

,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values),Money Raised (Values in USD),Industries_list,industry group list,17 Industry Categories
0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware,USD,1.100000e+07,1.100000e+07,"[Finance, Financial Services, FinTech, Software]","[Financial Services, Financial Services, Finan...","[Finance, Information Technology]"
1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...,USD,2.700000e+09,2.700000e+09,"[Automotive, Electric Vehicle, Manufacturing, ...","[Manufacturing, Transportation, Transportation...","[Transportation, Manufacturing and Agriculture]"
2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...,USD,9.400000e+06,9.400000e+06,"[Bitcoin, Cryptocurrency, Financial Exchanges,...","[Blockchain and Cryptocurrency, Blockchain and...","[Finance, Information Technology]"
3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...,USD,2.300000e+07,2.300000e+07,"[Billing, Finance, Financial Services, FinTech...","[Financial Services, Financial Services, Finan...","[Finance, Information Technology]"
4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...,USD,5.900000e+08,5.900000e+08,"[Aerospace, Air Transportation, Electric Vehic...","[Science and Engineering, Transportation, Tran...","[Transportation, Engineering and Biotech]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CAN,6.171000e+05,4.537500e+05,"[Banking, Debit Cards, Financial Exchanges, Fi...","[Financial Services, Financial Services, Finan...",[Finance]
1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,5.000000e+07,5.000000e+07,"[Information Technology, Logistics, SaaS]","[Information Technology, Software, Transportat...","[Transportation, Information Technology]"
1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech,USD,1.300000e+07,1.300000e+07,"[Banking, Financial Services, FinTech]","[Financial Services, Financial Services, Finan...",[Finance]
1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,3.500000e+07,3.500000e+07,"[Information Technology, Logistics, SaaS]","[Information Technology, Software, Transportat...","[Transportation, Information Technology]"
1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery,USD,6.600000e+06,6.600000e+06,"[Delivery, E-Commerce, Grocery]","[Administrative Services, Commerce and Shoppin...","[Consumer Goods and Retail, Support Service]"

In [152]:
combined_industry17 = pd.read_excel("investment cleanned final.xlsx")

In [153]:
# Add Announced Year and Country
combined_industry17['Location'] = combined_industry17['Location'].str.strip()

combined_industry17['Country'] = combined_industry17['Location'].apply(lambda x: x.split(', ')[-1] if isinstance(x, str) else None)
combined_industry17['City'] = combined_industry17['Location'].apply(lambda x: x.split(', ')[0] if isinstance(x, str) else None)
combined_industry17['Announced Date'] = combined_industry17['Announced Date'].astype(str)
combined_industry17['Announced Year'] = combined_industry17['Announced Date'].apply(lambda x: x.split('-')[0] if isinstance(x, str) else None)
combined_industry17

,Unnamed: 0,Investor,Announced Date,Organization Name,Lead Investor,Funding Round,Money Raised,Location,Industries,Money Raised (Currency Type),Money Raised (Values),Money Raised (Values in USD),Industries_list,industry group list,17 Industry Categories,Country,Announced Year,City
0,0,Abdul Latif Jameel,2022-10-13,Figopara,NaN,Series A - Figopara,$11M,"Istanbul, Istanbul, Turkey",Finance\nFinancial Services\nFinTech\nSoftware,USD,11000000,11000000,"['Finance', 'Financial Services', 'FinTech', '...","['Financial Services', 'Financial Services', '...","['Finance', 'Information Technology']",Turkey,2022,Istanbul
1,1,Abdul Latif Jameel,2021-01-19,Rivian,NaN,Series F - Rivian,$2.7B,"Plymouth, Michigan, United States",Automotive\nElectric Vehicle\nManufacturing\nT...,USD,2700000000,2700000000,"['Automotive', 'Electric Vehicle', 'Manufactur...","['Manufacturing', 'Transportation', 'Transport...","['Transportation', 'Manufacturing and Agricult...",United States,2021,Plymouth
2,2,Abdul Latif Jameel,2020-12-14,Rain,NaN,Series A - Rain,$9.4M,"Manama, Al Manamah, Bahrain",Bitcoin\nCryptocurrency\nFinancial Exchanges\n...,USD,9400000,9400000,"['Bitcoin', 'Cryptocurrency', 'Financial Excha...","['Blockchain and Cryptocurrency', 'Blockchain ...","['Finance', 'Information Technology']",Bahrain,2020,Manama
3,3,Abdul Latif Jameel,2020-12-08,Tabby,NaN,Series A - Tabby,$23M,"Riyadh, Ar Riyad, Saudi Arabia",Billing\nFinance\nFinancial Services\nFinTech\...,USD,23000000,23000000,"['Billing', 'Finance', 'Financial Services', '...","['Financial Services', 'Financial Services', '...","['Finance', 'Information Technology']",Saudi Arabia,2020,Riyadh
4,4,Abdul Latif Jameel,2020-01-16,Joby Aviation,NaN,Series C - Joby Aviation,$590M,"Santa Cruz, California, United States",Aerospace\nAir Transportation\nElectric Vehicl...,USD,590000000,590000000,"['Aerospace', 'Air Transportation', 'Electric ...","['Science and Engineering', 'Transportation', ...","['Transportation', 'Engineering and Biotech']",United States,2020,Santa Cruz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,1376,Zaeem Shaukat Mirza,2020-05-10,Manzil,No,Seed Round - Manzil,CA$617.1K,"Toronto, Ontario, Canada",Banking\nDebit Cards\nFinancial Exchanges\nFin...,CAN,617100,453750,"['Banking', 'Debit Cards', 'Financial Exchange...","['Financial Services', 'Financial Services', '...",['Finance'],Canada,2020,Toronto
1063,1377,Zamil Group,2022-02-10,Lyve Global,NaN,Convertible Note - Lyve Global,$50M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,50000000,50000000,"['Information Technology', 'Logistics', 'SaaS']","['Information Technology', 'Software', 'Transp...","['Transportation', 'Information Technology']",United Arab Emirates,2022,Abu Dhabi
1064,1378,Zamil Group,2021-02-23,Tarabut,NaN,Seed Round - Tarabut,$13M,"Dubai, Dubai, United Arab Emirates",Banking\nFinancial Services\nFinTech,USD,13000000,13000000,"['Banking', 'Financial Services', 'FinTech']","['Financial Services', 'Financial Services', '...",['Finance'],United Arab Emirates,2021,Dubai
1065,1379,Zamil Group,2020-06-04,Lyve Global,NaN,Series B - Lyve Global,$35M,"Abu Dhabi, Abu Dhabi, United Arab Emirates",Information Technology\nLogistics\nSaaS,USD,35000000,35000000,"['Information Technology', 'Logistics', 'SaaS']","['Information Technology', 'Software', 'Transp...","['Transportation', 'Information Technology']",United Arab Emirates,2020,Abu Dhabi
1066,1380,Zamil Group,2019-02-28,Nana,NaN,Series A - Nana,$6.6M,"Riyadh, Ar Riyad, Saudi Arabia",Delivery\nE-Commerce\nGrocery,USD,6600000,6600000,"['Delivery', 'E-Commerce', 'Grocery']","['Administrative Services', 'Commerce and Shop...","['Consumer Goods and Retail', 'Support Service']",Saudi Arabia,2019,Riyadh

In [154]:
combined_industry17.to_csv("investment cleanned final.csv")